---

- name: Update apt cache
  apt: update_cache=yes
  changed_when: False

- name: install apache
  apt: pkg={{ item }} state=present
  with_items:
   - apache2
   - php5-gd
   - libgd2-xpm-dev
   - libapache2-mod-php5
   - unzip

- name: Install Nagios prerequisites for Ubuntu
  apt: pkg={{ item }} state=present
  with_items:
   #- linux-headers-{{ ansible_kernel }}
   - build-essential
   - python-passlib

- name: setup-Debian | Remove Nagios3 and check-mk-livestatus for Ubuntu
  apt: pkg={{ item }} state=absent
  with_items:
   - nagios3
   - nagios3-core
   - check-mk-livestatus
  when: ansible_role_nagios_remove_packages

- name: Install Plugin prerequisites for Debian family
  apt: pkg={{ item }} state=present
  with_items:
   - libssl-dev
   - dnsutils
   - fping
   - libldap2-dev
   - libpq-dev
   - smbclient
   - gawk

- name: Install ansible prerequisites for Debian family
  apt: pkg={{ item }} state=present
  with_items:
   - python-urllib3 # fix SSL error when using ansible module get_url https://github.com/ansible/ansible/issues/23642

- name: Install Plugin prerequisites for Ubuntu
  apt: pkg={{ item }} state=present
  with_items:
   - libradiusclient-ng-dev
  when: ansible_distribution == 'Ubuntu'
